version: '3'
services:
  hadoop:
    image: "Projet-indice-qualite"
    ports:
      - "9870:9870"
    command: ["hadoop", "namenode"]
  spark:
    image: bitnami/spark:3
    ports:
      - "4040:4040"
  app:
    build: .
    volumes:
      - ./data:/data
    depends_on:
      - hadoop
      - spark
